require ["fileinto", "extlists", "vnd.proton.expire"];
require ["include", "environment", "variables", "relational", "comparator-i;ascii-numeric", "spamtest"];

# Prevent processing of messages that meet the spam threshold.
# [Generated by protonmail] Do not run this script on spam messages
if allof (environment :matches "vnd.proton.spam-threshold" "*",
spamtest :value "ge" :comparator "i;ascii-numeric" "${1}")
{
    return;
}


# Emails sent without a return path are typically system-generated.
if header :is "Return-Path" "<>" {
    fileinto "Not-a-human";  # label

    # No need to process further here.
}

# Continue with other filters
